// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XD8kGfEtAr5RDpdtRI5P0FVOKJsxgxo',
    appId: '1:140546834770:android:46e891725696b1620f7a8b',
    messagingSenderId: '140546834770',
    projectId: 'popu-5017d',
    storageBucket: 'popu-5017d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXIEx-ATD06EHY4Ry-bdVU10NHk6skio',
    appId: '1:140546834770:ios:731436606eb61e7f0f7a8b',
    messagingSenderId: '140546834770',
    projectId: 'popu-5017d',
    storageBucket: 'popu-5017d.firebasestorage.app',
    androidClientId: '140546834770-b4d6ha503hgeh4oinn861llfud4e96n0.apps.googleusercontent.com',
    iosClientId: '140546834770-ncvksa1d8nvprqebnju5fvpstbq58plc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tahadi',
  );
}
